name: Audit

on:
    schedule:
        - cron: '30 3 * * 3'

jobs:
    audit:
        runs-on: ubuntu-latest

        steps:
            # Setup env
            - uses: actions/checkout@v3
            - uses: webfactory/ssh-agent@v0.7.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 22

            - name: Run audit only high
              run: npm audit --no-color --level high > audit-high.txt || true

            - name: Run audit
              run: npm audit --no-color > audit-all.txt || true

            - name: Send mail
              uses: dawidd6/action-send-mail@v3.7.1
              with:
                  server_address: smtp.mailbox.org
                  server_port: 465
                  username: ${{secrets.REPORT_MAIL_USERNAME}}
                  password: ${{secrets.REPORT_MAIL_PASSWORD}}
                  subject: Audit-Report for ${{github.repository}}
                  # Read file contents as body:
                  body: file://audit-high.txt
                  to: devops@refinio.net,erik@refinio.net,winpuc@refinio.net,milena@refinio.net
                  from: devops@refinio.net # <user@example.com>
                  # Optional content type (defaults to text/plain):
                  content_type: text
                  # Optional attachments:
                  attachments: audit-all.txt
