name: Generate & deploy documentation

on:
    release:
        types: [published]

jobs:
    documentation:
        runs-on: ubuntu-latest

        steps:
            # Setup env
            - uses: actions/checkout@v3
            - uses: webfactory/ssh-agent@v0.7.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 22

            - name: Cache Node Modules
              id: cache-node-modules
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: node-modules-${{ hashFiles('package-lock.json') }}

            - name: Install if cache-miss
              if: steps.cache-node-modules.outputs.cache-hit != 'true'
              run: npm install

            - name: Build if cache-hit
              if: steps.cache-node-modules.outputs.cache-hit == 'true'
              run: npm run build

            - name: Build doc
              run: npm run make-docs

            - uses: aws-actions/configure-aws-credentials@v1-node16
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: eu-central-1

            - name: Set filename
              id: release_info
              run: echo "filename=${{ github.event.repository.name }}-doc-dev.tar.gz" >> $GITHUB_OUTPUT

            - name: Package zip
              run: |
                  tar -czvf ${{steps.release_info.outputs.filename}} doc

            - name: Upload to s3
              run: >
                  aws s3 cp ${{steps.release_info.outputs.filename}} s3://refinio-artefacts --metadata
                  '{
                  "github-repository":"${{ github.repository }}",
                  "github-ref":"${{ github.ref }}",
                  "github-sha":"${{ github.sha }}"
                  }'

            # # AWS CodeDeploy
            - id: deploy
              uses: webfactory/create-aws-codedeploy-deployment@v0.4.0
            - uses: peter-evans/commit-comment@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  body: |
                      @${{ github.actor }} this was deployed as [${{ steps.deploy.outputs.deploymentId }}](https://console.aws.amazon.com/codesuite/codedeploy/deployments/${{ steps.deploy.outputs.deploymentId }}?region=eu-central-1) to group `${{ steps.deploy.outputs.deploymentGroupName }}`.
